### ISSUE TITLE
Increase the Performance rate of the template on GTMetrix

### ISSUE THREAD

**Issue by Sylhare** [Sylhare/Type-on-Strap#6]
So there is GTMetrix which is a website that rates the rapidity of your website online. The template is actually quoted at [B(82%)](https://gtmetrix.com/reports/sylhare.github.io/LBYd0XOI)

![gtmetrix](https://user-images.githubusercontent.com/20642750/32191835-c589ccaa-bd88-11e7-8ebf-a154c9b7925f.JPG)

It seems there are a couple of things that can be done to increase the performance, so we should address it here:
- [x]  Optimize images (rated F) #10 #12 
- [x]  Leverage browser caching (rated F) #8 
- [x]  Serve scaled images (rated C) #13 
- [x]  Defer parsing of JavaScript (rated C)
- [x]  Add Expires headers (rated F) #8

**Comment by Sylhare** [comment]
For the last one, to defer javascript parsing, since we're using librairies (JQuery, Bootstrap, Katex, Jekyll search) it is hard to combine them all in one. However for the other in template JS files (Navbar.js and Katex_init.js) we can associate them into a main.min.js (minified version).

**Comment by Sylhare** [comment]
![image](https://user-images.githubusercontent.com/20642750/33516796-c7dd7de4-d746-11e7-9bf5-275d0eec5f8c.png)

**Comment by sylhare** [comment]
Has been improved with #143
